# nixpacks.toml for Laravel + Tailwind (Filament)


[phases.setup]
# Install Node.js 22.x, Composer, Nginx, and PHP-FPM for Laravel and Tailwind build
nixPkgs = ["nodejs_22", "php83Packages.composer", "nginx", "php83", "php83Extensions.mbstring", "php83Extensions.zip", "php83Extensions.intl", "php83Extensions.fileinfo", "php83Extensions.gd", "php83Extensions.bcmath", "php83Extensions.pdo_mysql"]



[phases.build]
# Install PHP dependencies, then Node dependencies and build assets
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist",
  "npm install --no-progress --no-audit",
  "npm run build"
]



[phases.start]
# Start Nginx and PHP-FPM for production
cmd = "php-fpm -D && nginx -g 'daemon off;'"


[variables]
# Set the default port for Railway/Nixpacks
PORT = "8080"
