# nixpacks.toml for Laravel + Tailwind (Filament)

[phases.setup]
# Install Node.js 22.x and Composer for Laravel and Tailwind build
nixPkgs = ["nodejs_22", "composer"]


[phases.build]
# Install PHP dependencies, then Node dependencies and build assets
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist",
  "npm install --no-progress --no-audit",
  "npm run build"
]

[phases.start]
# Start the Laravel app (default command)
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
# Set the default port for Railway/Nixpacks
PORT = "8080"
